### ISSUE TITLE
NullPointerException from context.getActivity()!!

### ISSUE THREAD

**Issue by giandifra** [SceneView/sceneview-flutter#3]
Hi @ThomasGorisse, 

I receive a NullPointerException when I initialize the ArSceneView, this doesn't happen with SceneView or Sceneform. 

I created a branch to show the exception, [here](https://github.com/SceneView/sceneview-flutter/blob/b11628c747f129cf007286de95e471a2a2a9d677/android/src/main/kotlin/io/github/sceneview/sceneview_flutter/SceneViewWrapper.kt#L31) the line of error.

The error comes from the activity getter

```
protected val activity: ComponentActivity
        get() = try {
            findFragment<Fragment>().requireActivity()
        } catch (e: Exception) {
            context.getActivity()!! //HERE
        }
```

```
Unhandled Exception: PlatformException(error, null, null, java.lang.NullPointerException
        at io.github.sceneview.SceneView.getActivity(SceneView.kt:327)
        at io.github.sceneview.ar.ArSceneView.<init>(ArSceneView.kt:45)
        at io.github.sceneview.ar.ArSceneView.<init>(ArSceneView.kt:30)
        at io.github.sceneview.sceneview_flutter.SceneViewWrapper.<init>(SceneViewWrapper.kt:31) 
```

PS: i wrote you on discord

**Comment by AnByronV** [comment]
With the latest version, this problem is fixed. However, there's another problem with the engine
`
Exception configuring surface
                                                                                                    java.lang.IllegalStateException: Calling method on destroyed Engine
                                                                                                    	at com.google.android.filament.Engine.getNativeObject(Engine.java:759)
                                                                                                    	at com.google.android.filament.Engine.createSwapChain(Engine.java:391)
                                                                                                    	at com.google.android.filament.Engine.createSwapChain(Engine.java:369)
                                                                                                    	at io.github.sceneview.SceneView$SurfaceCallback.onNativeWindowChanged(SceneView.kt:734)
                                                                                                    	at com.google.android.filament.android.UiHelper.createSwapChain(UiHelper.java:578)
                                                                                                    	at com.google.android.filament.android.UiHelper.-$$Nest$mcreateSwapChain(Unknown Source:0)
                                                                                                    	at com.google.android.filament.android.UiHelper$1.surfaceCreated(UiHelper.java:413)
                                                                                                    	at android.view.SurfaceView.updateSurface(SurfaceView.java:903)
                                                                                                    	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:181)
                                                                                                    	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1098)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3375)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:911)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8668)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
`

**Comment by giandifra** [comment]
I will try it
